### ISSUE TITLE
tar issue

### ISSUE THREAD

**Issue by theovanerp** [singularityware/docker2singularity#44] opened 2018-11-06 18:37 UTC
Hi, I am getting a tar error while running singularityware/docker2singularity on a mac, running macOS Seirra. The first post I came across on the issue suggest I need to install bdstar. Can anyone confirm or provide another recommendation?

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/mriqc_singularity --privileged -t --rm singularityware/docker2singularity poldracklab/mriqc

Image Format: squashfs
Docker Image: poldracklab/mriqc

Inspected Size: 7627 MB

(1/10) Creating a build sandbox...
(2/10) Exporting filesystem...
tar: usr/local/miniconda/pkgs/ncurses-5.9-10/share/terminfo/X: Directory renamed before its status could be extracted

**Comment by albert500** [comment] 2018-11-07 20:15
I got the same error. Found a solution from this thread: https://github.com/coreos/bugs/issues/1095
Accordingly I manage to fix it by adding to the RUN:
```
apk add --update libarchive-tools && \
apk del tar && \
ln -sf $(which bsdtar) $(which tar)
```
and rebuild the image. It works well for me.

**Comment by bryan-lunt** [comment] 2019-01-08 23:13
+1

**Comment by kasbohm** [comment] 2019-01-16 19:16
I have the same issue on my Macs. Mojave.

**Comment by kasbohm** [comment] 2019-01-16 21:15
This is true wherever the image was created i.e. it does not matter if it is pulled from dockerhub or built locally on a Mac.

**Comment by bryan-lunt** [comment] 2019-01-16 21:17
I followed the instructions on the other thread. I created my own docker2singularity container using the `bsdtar` package, replaced the normal Linux tar with a shell script that would strip out some parameters that `bsdtar` couldn't handle, and then exec bsdtar.

**Comment by akialbert** [comment] 2019-01-17 02:03
True. My previous solution can still sometimes failed. Eventually I used this "tar" script instead:

```bash
#!/bin/bash
set -e

ORIGINAL_ARGS=("$@")
TRIMMED_ARGS=()
for arg; do
  if [ $arg != "--ignore-failed-read" ]; then
    TRIMMED_ARGS+=($arg)
  fi
done

/usr/bin/tar ${TRIMMED_ARGS[@]}

```

**Comment by zym1010** [comment] 2019-01-17 14:48
I encountered this issue on Mac, but this problem disappeared on a Docker installed in a CentOS7 VM. Maybe the problem is kernel related as well.

**Comment by jmansour** [comment] 2019-02-15 11:24
I'm also encountering this issue on OS X Mojave.  I've incorporated @akialbert's fixes in a container (jmansour/docker2singularity).

**Comment by gmfricke** [comment] 2019-02-20 23:46
This only started happening when I upgraded to the latest singularity2docker today. The previous version I was using worked fine.

**Comment by vsoch** [comment] 2019-05-24 16:24
hey everyone apologies I haven't been watching the repository and missed this entire thread! I've just updated the build for version 3.1, and have a few questions for moving forward:

 - what versions/s do you need supported?
 - is there a solution that would work across OS / architecture that we could implement?

I'd like to put in changes to address your issue - worst case (if the second point is a "no") is that we have a branch / tag for macos. Let me know.

**Comment by vsoch** [comment] 2019-07-18 17:20
Can anyone comment if this is still an issue? If so, which branches?

**Comment by nathanweeks** [comment] 2019-07-18 19:34
The v3.1 release seemed to resolve this issue for the problematic Docker images I had encountered.

**Comment by vsoch** [comment] 2019-07-18 20:16
Cool, thanks @nathanweeks. I'm going to close the issue for now - if anyone that needs an older version runs into issues, please ping me and I'll get to it right away.

**Closed** 2019-07-18 20:17 UTC
